on:
  schedule:
    - cron: '0 */6 * * *'
  push:
    paths:
      - '.github/workflows/job_get_assets.yml'

jobs:

  get_assets:
    name: get_assets
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}
      API_SECRET: ${{ secrets.API_SECRET }}
      BQ_PROJECT_ID: ${{ secrets.BQ_PROJECT_ID }}
      SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-v2-${{ hashFiles('**/Cargo.lock') }}-${{ github.sha }}
          restore-keys: ${{ runner.os }}-cargo-v2-
      - uses: actions-rs/cargo@v1
        with:
          command: run
          args: assets
      - uses: actions-rs/cargo@v1
        with:
          command: run
          args: ticker

